# Docker compose file for BotArcAPI

version: '3'

services:
  botarcapi:
    build: .
    restart: always
    container_name: 'botarcapi'
    environment:
      BOTARCAPI_CONFIG: |
        {
          SERVER_PORT: 80
          ARCAPI_VERSION: 11,
          ARCAPI_APPVERSION: '2.6.1c',
          ARCAPI_USERAGENT: 'WeLoveArcaea (Linux; U; Android 2.3.3; BotArcAPI)',
          DATABASE_PATH: '/usr/botarcapi/savedata',
          LOG_LEVEL: 0,
          LOG_PATH: '/usr/botarcapi/savelogs'
        }
    ports:
      - '8000:80'
    
